@startuml

class Product {
    name: string
    price: float

    get_product_name() : string
    get_product_price() : int
}

note right of Product
    A product is the name of an item with a price.
end note

class ProductQuantity {
    product: Product
    quantity: int

    reduce_quantity_by_one()
    out_of_stock() : boolean
}

class ProductManager {
    product_price_stocks: list<ProductPriceStock>

    get_product_price(product_name) : float
    get_product_name(product_name) : string
    get_product_quantity(product_name) : int
    remove_one_product(product_name)(find product stock from product name and minus 1 to quantity)
}

@enduml